name: Daily Job

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every two minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run your application
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: npm start

      - name: Check for Uncommitted Changes
        id: changes
        run: |
          if git diff-index --quiet HEAD; then
            echo "::set-output name=has_changes::false"
          else
            echo "::set-output name=has_changes::true"
          fi

      - name: Commit and Push Changes
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git config --global user.email "aryamohanan.online@gmail.com"
          git config --global user.name "GitHub Action"
          
          # Ensure no errors if branch already exists
          git checkout -b version-updates || git checkout version-updates
          
          # Stage, commit, and push changes
          git add .version
          git commit -m "Update .version file"
          git push origin version-updates

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update .version file"
          title: "Update .version file"
          body: |
            Automatic update of .version file by GitHub Actions.
          head-branch: "version-updates"
          base: "main"  # This should be the target branch for the PR
